---
name: Build CI
on: [push]  # yamllint disable-line rule:truthy
jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Windows MSVC",
            enabled: 1,
            os: windows-latest,
            deps1: "",
            config: "cmake
                    -B build
                    -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
                    -DRTOSC_WERROR=1
                    -DCMAKE_BUILD_TYPE=Release
                    ",
            build: "cmake --build build --config Release",
            test: "ctest --output-on-failure --test-dir build -C Release"
          }
          - {
            name: "MinGW",
            enabled: 1,
            os: ubuntu-latest,
            update: "sudo apt-get update",
            deps1: "sudo apt-get install -y mingw-w64 cmake ninja-build wine64",
            deps2: "./build-mingw-deps $RUNNER_TEMP",
            config: "PKG_CONFIG_PATH=$RUNNER_TEMP/prefix/lib/pkgconfig
                     cmake
                     -S .
                     -B build
                     -G Ninja
                     -DRTOSC_WERROR=ON
                     -DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/mingw64.cmake
                     -DMINGW_PREFIX=$RUNNER_TEMP/prefix
                     -DCMAKE_BUILD_TYPE=Debug
                     ",
            build: "cmake --build build --config Debug",
            test: "ctest --output-on-failure --test-dir build"
          }
          - {
            name: "Ubuntu gcc",
            enabled: 1,
            os: ubuntu-latest,
            deps1: "sudo apt-get install liblo-dev",
            config: "cd build && cmake -DRTOSC_WERROR=1 ..",
            build: "cd build && make",
            test: "cd build && ctest --output-on-failure"
          }
          - {
            name: "Ubuntu clang+lld",
            enabled: 1,
            os: ubuntu-latest,
            deps1: "sudo apt-get install liblo-dev",
            config: "cd build &&
                    cmake
                    -DRTOSC_WERROR=1
                    -DCMAKE_C_COMPILER=clang
                    -DCMAKE_CXX_COMPILER=clang++
                    -DCMAKE_SHARED_LINKER_FLAGS='-fuse-ld=lld'
                    -DCMAKE_EXE_LINKER_FLAGS='-fuse-ld=lld'
                    ..",
            build: "cd build && make",
            test: "cd build && ctest --output-on-failure"
          }
          - {
            name: "macOS clang",
            enabled: 1,
            os: macos-latest,
            deps1: "brew install liblo",
            config: "cd build && cmake -DRTOSC_WERROR=1 ..",
            build: "cd build && make",
            test: "cd build && ctest --output-on-failure"
          }
    steps:
      - name: check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: update system
        if: ${{ matrix.config.enabled == 1 }}
        run: ${{ matrix.config.update }}
      - name: install deps (1)
        if: ${{ matrix.config.enabled == 1 }}
        run: ${{ matrix.config.deps1 }}
      - name: install deps (2)
        if: ${{ matrix.config.enabled == 1 }}
        run: ${{ matrix.config.deps2 }}
      - name: create build directory
        if: ${{ matrix.config.enabled == 1 }}
        run: mkdir build
      - name: configure
        if: ${{ matrix.config.enabled == 1 }}
        run: ${{ matrix.config.config }}
      - name: make
        if: ${{ matrix.config.enabled == 1 }}
        run: ${{ matrix.config.build }}
      - name: make test
        if: ${{ matrix.config.enabled == 1 }}
        run: ${{ matrix.config.test }}
